version: '3'

services:
  elasticsearch:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx4096m -Xms2048m"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    restart: always
    image:
      "kibana:7.6.0"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  logstash:
    restart: always
    image:
      "logstash:7.6.0"
    volumes:
      - ./config/logstash_file.conf:/usr/share/logstash/config/logstash.conf
      - /Volumes/github/namu_wiki_parser/document/:/data/
    ports:
      - 5000:5000
      - 9600:9600
    entrypoint: ["/usr/local/bin/docker-entrypoint", "-f", "/usr/share/logstash/config/logstash.conf"]
